zakovat_log/urls.py
from django.contrib import admin
from django.urls import path
from main.views import *

urlpatterns = [
    path('onlyforme/', admin.site.urls),
    path('',Registration,name='index'),
    path('error/',ErrorAll,name='error'),
    path('count-error/',ErrorCount,name='count-error'),
    path('team-error/',ErrorTeam,name='team-error'),
    path('success/',Success,name='success'),
    path('teams/',Table,name='table'),
    path('full-team/',FullTeamError,name='full')
]

main/models.py
from django.db import models


class RegistrationTeam(models.Model):
    fullname = models.CharField(max_length=255)
    team_name = models.CharField(max_length=50,unique=True)
    username = models.CharField(max_length=255)
    count = models.IntegerField()
    STATUS = (
        (1,"Ro'yhatdan o'tgan"),
        (2,"Ro'yhatdan o'tmagan")
    )
    choice = models.IntegerField(choices=STATUS,default=1)

main/views.py
from django.conf import settings
from django.shortcuts import render,redirect
from .models import *


def Registration(request):
    if request.method == 'POST':
        cap_name = request.POST.get('cap_name')
        team_name = request.POST.get('team_name')
        username = request.POST.get('username')
        count = request.POST.get('count')
        if RegistrationTeam.objects.filter(team_name=team_name) and int(count) > 8 or int(count) < 2:
            return redirect('error')
        if int(count) > 8 or int(count) < 2:
            return redirect('count-error')
        if RegistrationTeam.objects.filter(team_name=team_name):
            return redirect('team-error')

        total = 0
        for i in RegistrationTeam.objects.all():
            total+=1

        if int(total) > 24:
            return redirect('full')
        else:
            RegistrationTeam.objects.create(fullname=cap_name, team_name=team_name, username=username, count=count)
            return redirect('success')


    return render(request,'index.html')

def FullTeamError(request):
    return render(request,'full.html')

def ErrorCount(request):
    return render(request,'count_error.html')

def ErrorTeam(request):
    return render(request,'team_error.html')

def ErrorAll(request):
    return render(request,'error.html')

def Success(request):
    return render(request,'success.html')

def Table(request):
    context = {
        'team':RegistrationTeam.objects.all()
    }
    return render(request,'table.html',context)

templates/count_error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'error.css' %}">
    <script src="{% static 'js/first.js' %}"></script>
</head>
<body>
<div class="text">
  <div>Ishtirokchi sonini kiritishda hatolik !!!</div>
  <h1>Maximum 8ta</h1>
  <hr>
  <div><a href="{% url 'index' %}"style="color:lightblue;">Qaytish uchun bosing</a></div>
</div>

<div class="astronaut">
  <img src="https://images.vexels.com/media/users/3/152639/isolated/preview/506b575739e90613428cdb399175e2c8-space-astronaut-cartoon-by-vexels.png" alt="" class="src">
</div>
</body>
</html>

templates/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'error.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<div class="text">
  <div>Bunday jamoa nomi mavjud va ishtirokchilar 8 tadan ko'p yoki 2 tadan kam !!!</div>
  <h1>Jamoa nomida va ishtirokchi sonida hatolik</h1>
  <hr>
  <div><a href="{% url 'index' %}"style="color:lightblue;">Qaytish uchun bosing</a></div>
</div>

<div class="astronaut">
  <img src="https://images.vexels.com/media/users/3/152639/isolated/preview/506b575739e90613428cdb399175e2c8-space-astronaut-cartoon-by-vexels.png" alt="" class="src">
</div>
</body>
</html>

templates/full.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'error.css' %}">
    <script src="{% static 'js/first.js' %}"></script>
</head>
<body>
<div class="text">
  <div>Jamoalar uchun joylar to'lgan</div>
  <h1>Afsus ulgira olmadingiz :(</h1>
  <hr>
  <div><a href="{% url 'index' %}"style="color:lightblue;">Qaytish uchun bosing</a></div>
</div>

<div class="astronaut">
  <img src="https://images.vexels.com/media/users/3/152639/isolated/preview/506b575739e90613428cdb399175e2c8-space-astronaut-cartoon-by-vexels.png" alt="" class="src">
</div>
</body>
</html>

templates/index.html
  {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zakovat Ziyolilari</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="login-box">
  <h2>Zakovat uchun ro'yhatdan o'tish!</h2>
  <form action="{% url 'index' %}" method="post">
    {% csrf_token %}
    <div class="user-box">
      <input type="text" name="cap_name" required="">
      <label>Jamoa sardorining ismi va familyasi:</label>
    </div>
    <div class="user-box">
      <input type="text" name="team_name" required="">
      <label>Jamoa nomi:</label>
    </div>
      <div class="user-box">
      <input type="text" name="username" required="">
      <label>Telegram username:</label>
    </div>
      <div class="user-box">
      <input type="text" name="count" required="">
      <label>Ishtirokchilar soni(min:2 Max:8):</label>
    </div>
    <button type="submit" style=" background: rgba(0,0,0,.5);">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Yuborish
  </button>
  </form>
</div>
</body>
</html>







MENGA NIMA

templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Muvaffaqiyat</title>
  <link rel="stylesheet" href="{% static 'success.css' %}">
</head>
<body>
<div class="wrapperAlert">

  <div class="contentAlert">

    <div class="topHalf">

      <p><svg viewBox="0 0 512 512" width="100" title="check-circle">
        <path d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z" />
        </svg></p>
      <h1> Muvaffaqiyatli o'tdingiz</h1>

     <ul class="bg-bubbles">
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
       <li></li>
     </ul>
    </div>

    <div class="bottomHalf">

      <p>Ro'yhatdan o'tgan barcha jamoalarni ko'rishingiz mumkin</p>

      <a href="{% url 'table' %}"> <button id="alertMO">Ko'rish</button></a>

    </div>

  </div>

</div>
</body>
</html>

templates/table.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Jamoalar</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">

			</div>
			<div class="row">
				<div class="col-md-12">
					<h4 class="text-center mb-4">Ro'yhatdan o'tgan jamoalar</h4>
					<div class="table-wrap">
						<table class="table">
					    <thead class="thead-primary">
					      <tr>
					        <th>Tartib raqam</th>
					        <th>Jamoa nomi</th>
					        <th>Jamoa sardori</th>
					        <th>Ishtirokchilar soni</th>
					        <th>Status</th>
						      </tr>
					    </thead>
					    <tbody>
						{% for i in team %}
					      <tr>
					        <th scope="row" class="scope" >#{{forloop.counter}}</th>
					        <td>{{i.team_name}}</td>
					        <td>{{i.fullname}}</td>
					        <td>{{i.count}} ta</td>
							  {% if i.choice == 1 %}
					        <td><a href="" class="btn btn-success" disabled>{{ i.get_choice_display }}</a></td>
							{% else %}
					        <td><a href="" class="btn btn-danger" disabled>{{ i.get_choice_display }}</a></td>
							  {% endif %}
					      </tr>
						{% endfor %}


					    </tbody>
					  </table>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/team_error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'error.css' %}">
    <script src="{% static 'js/first.js' %}"></script>
</head>
<body>
<div class="text">
  <div>Bunday nomlik jamoa mavjud !!!</div>
  <h1>Jamoa nomida hatolik!</h1>
  <hr>
  <div><a href="{% url 'index' %}"style="color:lightblue;">Qaytish uchun bosing</a></div>
</div>

<div class="astronaut">
  <img src="https://images.vexels.com/media/users/3/152639/isolated/preview/506b575739e90613428cdb399175e2c8-space-astronaut-cartoon-by-vexels.png" alt="" class="src">
</div>
</body>
</html>